# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-27 08:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('foodId', models.IntegerField(default=1, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default Title', max_length=200)),
                ('brand', models.CharField(default='Default Title', max_length=200)),
            ],
        ),
    ]
